### PR TITLE
Remove non-working providers and types

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by wbclark** [comment]
```
Error: Execution of '/usr/bin/katello-ssl-tool --gen-ca -p file:/etc/pki/katello/private/katello-default-ca.pwd --force --ca-cert-dir /etc/pki/katello-certs-tools/certs --set-common-name centos7-64.example.com --ca-cert katello-default-ca.crt --ca-key katello-default-ca.key --ca-cert-rpm katello-default-ca --set-country US --set-state North Carolina --set-city Raleigh --set-org Katello --set-org-unit SomeOrgUnit --set-email  --cert-expiration 36500' returned 1: Traceback (most recent call last):

    File "/usr/bin/katello-ssl-tool", line 5, in <module>

      from pkg_resources import load_entry_point

  ImportError: No module named pkg_resources
```

**Comment by wbclark** [comment]
I reviewed the removed files and I believe the above error is not related. I'll try re-running the tests.

**Comment by ehelms** [comment]
I have seen this error on other PRs that then fixed itself. An intermittent issue I believe but not clear to me where the issue lies (the package or the infra)

**Comment by ekohl** [comment]
Perhaps it's not installing setuptools then?

**Comment by ekohl** [comment]
> Perhaps it's not installing setuptools then?

https://github.com/theforeman/foreman-packaging/pull/5459

**Comment by ekohl** [comment]
Normally this would be a breaking change but since these types have been broken for ages I'm leaving it unlabeled.

**Pull request merged**
