### PR TITLE
Release 21.1.0

### PR DESCRIPTION
**Pull request by ehelms**
Pending release PRs:

- [x] https://github.com/theforeman/puppet-katello/pull/431

### CODE REVIEW

**Comment by ekohl** [comment]
I still think we need to know if this needs modification:
https://github.com/theforeman/puppet-katello/blob/52770f0d2cdcd4ed86b889f4913735ab17a57741/templates/katello.yaml.erb#L14
Either it's redundant and we can drop the whole block or it needs to be configurable now that OSTree is back again.
(guess why I submitted #432)

**Comment by ehelms** [comment]
> I still think we need to know if this needs modification:
> 
> https://github.com/theforeman/puppet-katello/blob/52770f0d2cdcd4ed86b889f4913735ab17a57741/templates/katello.yaml.erb#L14
> 
> 
> Either it's redundant and we can drop the whole block or it needs to be configurable now that OSTree is back again.
> (guess why I submitted #432)

@jlsherrill can you comment on this for us? Is this entry being re-used and is it needed for the new ostree work?

**Comment by jlsherrill** [comment]
oh all of those content_type definitions can go away now !  We figure it out dynamically

**Comment by ekohl** [comment]
Great, since which version?

**Comment by jlsherrill** [comment]
since katello 4.2    https://projects.theforeman.org/issues/31616

**Comment by ekohl** [comment]
I've opened https://github.com/theforeman/puppet-katello/pull/433 and https://github.com/theforeman/foreman-installer/pull/730 to reflect that.

**Comment by ehelms** [comment]
Updated

**Review by ekohl — APPROVED** [review]

**Pull request merged**
