### PR TITLE
Refs #29817 - Implement a resizable hosts_queue pool

### PR DESCRIPTION
**Pull request by ekohl**
This uses the new foreman::dynflow::pool defined type which allows users to easily add additional workers or scale them back.

Currently a draft since it's pointing to my branch in the fixtures to allow testing. Blocked on https://github.com/theforeman/puppet-foreman/pull/843.

### CODE REVIEW

**Comment by ehelms** [comment]
https://github.com/theforeman/puppet-foreman/pull/843 allows users to control the concurrency and the number of workers, here I only see number of workers, is that an intended design to restrict it for this use case?

**Comment by ekohl** [comment]
Not intentional, just a rushed patch here. @ianballou could you have a look about the desired config options and if this properly replaces your patch?

Also looks like I messed up the fixtures. Will update both once there's clarity about which params are expected.

**Comment by ianballou** [comment]
@ekohl, it looks like this PR sufficiently covers my old one :+1:

**Comment by ianballou** [comment]
I'm curious what's going on with this PR, I haven't checked-in for a while.  As far as I know we'd still like this functionality for Pulp 3, but someone can let me know if we don't.

**Comment by ehelms** [comment]
This can now be updated with https://github.com/theforeman/puppet-foreman/pull/843 having been merged

**Comment by ekohl** [comment]
Rebased to resolve merge conflicts and it depends on theforeman/foreman 17.x to ensure the correct API is present.

**Review by ehelms — APPROVED** [review]

**Pull request merged**
