### PR TITLE
Fixes #29664: Update Candlepin port to new default

### PR DESCRIPTION
**Pull request by ehelms**
Does not "require" https://github.com/theforeman/puppet-candlepin/pull/156 but I would like them to be in sync default wise and resolve the port number conversation.

### CODE REVIEW

**Comment by ekohl** [comment]
I'd like to get https://github.com/theforeman/puppet-katello/pull/339 in before this

**Comment by ehelms** [comment]
From my testing, this will require SELinux changes. @lzap can you help with that when you have time? I imagine they would be in the katello-selinux policy.

**Comment by ehelms** [comment]
Tested full install piepline with the SELinux change here -- https://github.com/Katello/katello-selinux/pull/26

```
[root@pipeline-katello-server-nightly-centos7 vagrant]# netstat -nlp | grep 23443
tcp6       0      0 127.0.0.1:23443         :::*                    LISTEN      26510/java          
[root@pipeline-katello-server-nightly-centos7 vagrant]# netstat -nlp | grep 8443
```

**Comment by ehelms** [comment]
The commit was already fixes but I updated the MR title to reflect the same. This is waiting on final review of https://github.com/Katello/katello-selinux/pull/29

**Review by ekohl — APPROVED** [review]

**Comment by ekohl** [comment]
I'm labeling this as backwards incompatible because I think this deserves a major version bump. I don't want to risk accidentally cherry picking a minor version in a stable release.

**Pull request merged**
