### PR TITLE
Support use_pulp_2_for_deb

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
we still need to handle apache configuration, and upgrade/migrations but this is a start

**Comment by jlsherrill** [comment]
@sbernhard  pinging for awareness

**Comment by sbernhard** [comment]
Thank you for letting me know.

**Comment by ekohl** [comment]
> we still need to handle apache configuration, and upgrade/migrations but this is a start

FYI: we greatly refactored how we do this. It's now all in [puppet-pulpcore](https://github.com/theforeman/puppet-pulpcore) and plugins provide a single boolean (like [rpm](https://github.com/theforeman/puppet-pulpcore/blob/bb0b65a69dbada288b069494e45a1800745c5f7d/manifests/plugin/rpm.pp#L5)). That's set in [puppet-foreman_proxy_content](https://github.com/theforeman/puppet-foreman_proxy_content) (like [here](https://github.com/theforeman/puppet-foreman_proxy_content/blob/a620f4115514a9fed26c4815e9eff1442b380c87/manifests/init.pp#L416-L418)).

**Review by ekohl — APPROVED** [review]
I'm not sure if this is still blocked on anything.

**Review by sbernhard — APPROVED** [review]

**Comment by jlsherrill** [comment]
I think all we need still is the upgrade/migration in foreman-installer, but its probably not blocked on it.  I'll try to get to that today

**Pull request merged**
